version: "3.8"

services:
    postgres:
        container_name: hastepaste_postgres
        image: postgres
        environment:
            POSTGRES_USER: hastepaste
            POSTGRES_PASSWORD: hastepaste
            PGDATA: /data/postgres
        volumes:
            - ./postgres:/data/postgres
        ports:
            - 5432:5432
        networks:
            - postgres
        restart: unless-stopped

    pgadmin:
        container_name: hastepaste_pgadmin
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: pg@hastepaste.xyz
            PGADMIN_DEFAULT_PASSWORD: hastepaste
            PGADMIN_CONFIG_SERVER_MODE: "False"
        volumes:
            - ./pgadmin:/var/lib/pgadmin
        ports:
            - 5050:80
        networks:
            - postgres
        restart: unless-stopped

networks:
    postgres:
